parameters: {}
environment: {}
packages:
  - name: lethebot
    shared: false
    environment: {
      TG_SESSION_STR: '${TG_SESSION_STR}',
      TG_API_ID: '${TG_API_ID}',
      TG_API_HASH: '${TG_API_HASH}',
      TG_BOT_TOKEN: '${TG_BOT_TOKEN}',
      INVITE_CODE: '${INVITE_CODE}',
      DB_PASSWORD: '${DB_PASSWORD}',
      DB_PATH: '${DB_PATH}'
    }
    functions:
      - name: tg_webhook
        runtime: python:3.9
        main: ""
        web: true
        triggers:
          - name: daily_batch
            sourceType: scheduler
            sourceDetails:
              cron: '${SCHEDULE_CRON_UTC}'
              withBody: '{"triggerType": "daily_batch"}'
        limits:
          timeout: 30000
          memory: 256
